/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    AInput: typeof import('ant-design-vue/es')['Input']
    AQrcode: typeof import('ant-design-vue/es')['QRCode']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ASpace: typeof import('ant-design-vue/es')['Space']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

// For TSX support
declare global {
  const AButton: typeof import('ant-design-vue/es')['Button']
  const AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
  const AInput: typeof import('ant-design-vue/es')['Input']
  const AQrcode: typeof import('ant-design-vue/es')['QRCode']
  const ASelect: typeof import('ant-design-vue/es')['Select']
  const ASpace: typeof import('ant-design-vue/es')['Space']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
}